name: test-04-avalonia
on:
  pull_request:
    branches: [feat/04-avalonia]

jobs:
  test-04-avalonia:
    if: true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Build solution
        working-directory: ./src
        run: dotnet build

      - name: Run all tests
        working-directory: ./src
        run: dotnet test -c Release

      - name: Check report existence
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "docs/04-avalonia/report.md"

      - name: Report exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          echo Missing report: docs/04-avalonia/report.md
          exit 1
