name: test-03-async-grpc
on:
  pull_request:
    branches: [feat/03-async-grpc]

jobs:
  test-03-async-grpc:
    if: true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Build solution
        working-directory: ./src
        run: dotnet build

      - name: Test prepare
        working-directory: ./src
        run: dotnet test test-00-prepare -c Release

      - name: Test basic
        working-directory: ./src
        run: dotnet test test-01-basic -c Release

      - name: Test multithreading
        working-directory: ./src
        run: dotnet test test-02-multithreading -c Release

      - name: Test async-grpc
        working-directory: ./src
        run: dotnet test test-03-async-grpc -c Release

      - name: Check report existence
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "docs/03-async-grpc/report.md"

      - name: Report exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          echo Missing report: docs/03-async-grpc/report.md
          exit 1
